package models

// NodeStatus stores relevant node info status.
// Generated by https://mholt.github.io/json-to-go/
type NodeStatus struct {
	Ready       bool   `json:"ready"`
	ReadyS      string `json:"ready_s"`
	StatusS     string `json:"status_s"`
	Port        int    `json:"port"`
	Locked      bool   `json:"locked"`
	Timestamp   int    `json:"timestamp"`
	Version     string `json:"version"`
	Netprotocol struct {
		Ver  int `json:"ver"`
		VerA int `json:"ver_a"`
	} `json:"netprotocol"`
	Blocks   int `json:"blocks"`
	Netstats struct {
		Active    int `json:"active"`
		Clients   int `json:"clients"`
		Servers   int `json:"servers"`
		ServersT  int `json:"servers_t"`
		Total     int `json:"total"`
		Tclients  int `json:"tclients"`
		Tservers  int `json:"tservers"`
		Breceived int `json:"breceived"`
		Bsend     int `json:"bsend"`
	} `json:"netstats"`
	Nodeservers []struct {
		IP       string `json:"ip"`
		Port     int    `json:"port"`
		Lastcon  int    `json:"lastcon"`
		Attempts int    `json:"attempts"`
	} `json:"nodeservers"`
}
